[package]
name = "filecryption"
version = "0.9.32"
edition = "2024"
rust-version = "1.92.0"
description = "Allows encryption and decryption of files using Argon2 and XChaCha20Poly1305"
repository = "https://github.com/Voornaamenachternaam/filecryption"
homepage = "https://github.com/Voornaamenachternaam/filecryption"
license-file = "LICENSE.txt"
keywords = ["encryption", "decryption", "XChaCha20Poly1305"]
categories = ["cryptography"]
publish = false

[dependencies]
# rust-crypto = "^0.2.36"
orion = { version = "^0.17.12", features = ["default"] }
base64 = "^0.22.1"
#crossterm = "^0.29.0"
rpassword = "^7.4.0"
#inotify = "^0.11.0"
tokio = "^1.49.0"
clap = { version = "^4.5.54", features = ["derive"] }
zeroize = { version = "^1.8.2", features = ["zeroize_derive"] }
#opaque-ke = "^4.0.1"
rand = "^0.9.2"

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
